# APPLICATION
app:
  routing:
    name: ${APP_NAME}
    version: ${APP_VERSION}
    destinations: ${APP_ROUTING_DESTINATION}

# OPENTRACING
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED}
    log-spans: true
    http-sender:
      url: ${JAEGER_COLLECTOR}
    service-name: ${APP_NAME}-${APP_VERSION}